name: Example - Azure login 

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  azure-nonprod:
    runs-on: ubuntu-latest
    environment: nonprod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login via Azure OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}  
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Confirm Azure Login
        run: |
          az account show

  azure-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: azure-nonprod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login via Azure OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}  
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Confirm Azure Login
        run: |
          az account show